#include <windows.h>
#include <iostream>
#include <string>
#include <Shlwapi.h>
#include <random>
#include <vector>
#include <stdio.h>
#include <stdlib.h>
#include <fstream>
#include <sstream>
#include <WinInet.h>
#include <iomanip>
#include <cstdio> 
#include <WinUser.h>
#include "wininet.h"
#include <WinBase.h>
#include <tchar.h>